volumes:
  wordpress:
  mariadb:

networks:
  inception:
    driver: bridge

services:
  wordpress:
    container_name: wordpress
    build: ./wordpress/
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./mariadb/
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    build: ./nginx/
    volumes:
      - wordpress:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
