volumes:
  web:

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./nginx/.
    image: nginx:42
    ports:
     - "443:443"
    volumes:
      - ./web:/var/www/html
    restart: always
  wordpress:
    build: ./wordpress/.
    container_name: wp-php
    image: wordpress:42
    volumes:
      - ./web:/var/www/html
    restart: always
