volumes:
  web:

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./nginx/.
    image: nginx:42
    ports:
     - "443:443"
    volumes:
      - ./web:/var/www/html
    env_file:
      - .env
    restart: always

  wordpress:
    build: ./wordpress/.
    container_name: wordpress
    image: wordpress:42
    ports:
      - "9000:9000"
    volumes:
      - ./web:/var/www/html
    env_file:
      - .env
    restart: always

  #  mariadb:
  #  build: ./mariadb/.
    #    container_name: mariadb
    #    env_file:
#      - .env
